from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent
OUTPUT_DIR = BASE_DIR / "outputs"
OUTPUT_DIR.mkdir(exist_ok=True)

DEFAULT_INTERVAL = "4hour"

VWLM_FAST_EMA = 18
VWLM_SLOW_EMA = 42
VWLM_ADX_THRESHOLD = 20
VWLM_RSI_THRESHOLD = 50
VWLM_ATR_WINDOW = 20
VWLM_ADX_WINDOW = 20
VWLM_RSI_WINDOW = 14
VWLM_VOLUME_MA = 20

VB_MEDIAN_WINDOW = 42
VB_ADX_WINDOW = 20
VB_ATR_WINDOW = 20
VB_ADX_THRESHOLD = 20
VB_VOLUME_MA = 20
VB_VOLUME_MULTIPLIER = 1.2
INSTRUMENTS = {
    "RELIANCE": 738561,
    "TCS": 2953217,
    "INFY": 408065,
    "HDFCBANK": 341249
}
